@startuml

usecase UC001 as "Log in to
the application"

usecase UC002 as "Add places"

usecase UC003 as "Add remote devices"

usecase UC004 as "Assign
remote devices
to a place"

usecase UC005 as "Modify places"

usecase UC006 as "Modify
remote devices
information"

usecase UC007 as "View all
the information
of their places and
its remote devices"

usecase UC008 as "Update the
information
received from the
remote devices"

usecase UC009 as "Sign up 
in the
application"

User -up-> (UC001)
User -left-> (UC002)
User -down-> (UC003)
User -down-> (UC004)
User -left-> (UC005)
User -down-> (UC006)
User -down-> (UC007)
User -up-> (UC009)

Application -down-> (UC008) : have to

@enduml
